use_frameworks!

platform :ios, '8.0'

target 'SFCrashInspector_Example' do
  pod 'SFCrashInspector', :path => '../'

  target 'SFCrashInspector_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
